### ISSUE TITLE
/okazu

### ISSUE THREAD

**Issue by Cer0un0** [Cer0un0/discord-nene#5]
おかずチャンネルの過去おかずをランダムに返すコマンド

**Comment by Cer0un0** [comment]
ストップワードの作成が必要

**Comment by satory074** [comment]
komifloで、pageに関係なくURL変換するようにしてほしい
頼むよ～～～

**Comment by Cer0un0** [comment]
satory074様
ご要望どおり、pageに関係なくURLを変換できるよう改修致しました。
おかずのご提供をよろしくお願いいたします。
